services:
  # Infrastructure
  payguard-postgres:
    image: postgres:15
    container_name: payguard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - payguard_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: payguard-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: payguard-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: payguard-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Microservices
  api-gateway:
    build: ./api-gateway
    container_name: payguard-api-gateway
    ports:
      - "8089:8080"
    environment:
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      USER_SERVICE_URL: http://user-service:8081
      PAYMENT_SERVICE_URL: http://payment-service:8082
      FRAUD_ENGINE_URL: http://fraud-engine:8083
      NOTIFICATION_SERVICE_URL: http://notification-service:8084
    depends_on:
      - user-service
      - payment-service
      - fraud-engine
      - notification-service

  user-service:
    build: ./user-service
    container_name: payguard-user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payguard-postgres:5432/users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      payguard-postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  fraud-engine:
    build: ./fraud-engine
    container_name: payguard-fraud-engine
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payguard-postgres:5432/fraud
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      payguard-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started

  payment-service:
    build: ./payment-service
    container_name: payguard-payment-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payguard-postgres:5432/payments
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      FRAUD_ENGINE_URL: http://fraud-engine:8083
      STRIPE_API_KEY: sk_test_dummy_key
    depends_on:
      payguard-postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      fraud-engine:
        condition: service_started

  notification-service:
    build: ./notification-service
    container_name: payguard-notification-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payguard-postgres:5432/notifications
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: davidsaaka77@gmail.com
      SMTP_PASSWORD: Jobsearch@1234
      MANAGEMENT_HEALTH_MAIL_ENABLED: "false"
    depends_on:
      payguard-postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  reconciliation-service:
    build: ./reconciliation-service
    container_name: payguard-reconciliation-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payguard-postgres:5432/reconciliation
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STRIPE_API_KEY: sk_test_dummy_key
    depends_on:
      payguard-postgres:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  payguard_postgres_data: