apiVersion: v1
kind: ConfigMap
metadata:
  name: payguard-config
  namespace: payguard
data:
  # Database URLs
  USER_DB_URL: "jdbc:postgresql://postgres:5432/users"
  PAYMENT_DB_URL: "jdbc:postgresql://postgres:5432/payments"
  FRAUD_DB_URL: "jdbc:postgresql://postgres:5432/fraud"
  NOTIFICATION_DB_URL: "jdbc:postgresql://postgres:5432/notifications"
  RECONCILIATION_DB_URL: "jdbc:postgresql://postgres:5432/reconciliation"
  
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  
  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Service URLs (internal)
  USER_SERVICE_URL: "http://user-service:8081"
  PAYMENT_SERVICE_URL: "http://payment-service:8082"
  FRAUD_SERVICE_URL: "http://fraud-engine:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"
  RECONCILIATION_SERVICE_URL: "http://reconciliation-service:8085"
